### ISSUE TITLE
validateRfReference() fails in PHP 7.4 with invalid characters in reference number

### ISSUE THREAD

**Issue by sprain** [kmukku/php-iso11649#1]
In PHP 7.4, BCMath functions will now warn if a non well-formed number is passed, such as "32foo". See [Backward Incompatible Changes](https://www.php.net/manual/en/migration74.incompatible.php).

This results in an error when a reference with invalid characters is checked.

```
$referenceGenerator = new phpIso11649();
var_dump($referenceGenerator->validateRfReference('RF45123451234Ä'));

// Result in PHP 7.3
bool(false)

// Result in PHP 7.4
Warning: bcmod(): bcmath function argument is not well-formed in /var/www/html/vendor/kmukku/php-iso11649/src/phpIso11649.php on line 68
```

Likely, in a first step a check for only valid characters should take place before the replacement to numeric values happens.

**Comment by kmukku** [comment]
I see. Thanks for reporting it. Mind to create a pull request?

**Comment by sprain** [comment]
Great quick reply on a 3-year-old repository :)
Pull request is ready: https://github.com/kmukku/php-iso11649/pull/2

**Comment by kmukku** [comment]
I'm happy you found it useful. :)

**Comment by sprain** [comment]
Now all I need is a new release and we are golden :)
https://github.com/kmukku/php-iso11649/releases

**Comment by kmukku** [comment]
Done. Thanks!

**Comment by sprain** [comment]
One more thing: it needs to be updated on Packagist as well.
https://packagist.org/packages/kmukku/php-iso11649

**Comment by kmukku** [comment]
I think I managed to do it now. If more development is needed for the package, I'm happy to add more collaborators. :)
